# unexBGC configuration file

# Sample sheet
samples: "config/samples.tsv"

# Input data
input_dir: "data/raw"

# Output data
output_dir: "results"
# DAS Tool database
dastool_db: "/path/to/DAS_Tool/db"
# GTDB-Tk database
gtdbtk_db: "/path/to/gtdbtk/database"
# BiG-SCAPE Pfam database
bigscape_pfam: "/path/to/Pfam-A.hmm"

# Computational resources
threads:
  fastp: 12
  megahit: 24
  quast: 12
  bowtie2: 12
  concoct: 24
  metabat2: 24
  maxbin2: 24
  dastool: 24
  checkm2: 24
  antismash: 24
  bigscape: 24
