# unexBGC configuration file

# Sample sheet
samples: "config/samples.tsv"

# Input data
input_dir: "data/raw"

# Output data
output_dir: "results"

# Computational resources ######NOT FINAL VALUES JUST FOR STRUCTURE
threads:
  fastp: 12
  megahit: 24
  quast: 12
  bowtie2: 12
  antismash: 24
  concoct: 24
  metabat2: 24
  maxbin2: 24
